services:
  nginx:
    image: webide.azurecr.io/seng513-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped

  envoy:
    image: webide.azurecr.io/seng513-envoy:latest
    container_name: envoy
    ports:
      - "8081:8081" # gRPC-Web entry point
      - "9901:9901" # Envoy admin
    depends_on:
      - grpc-server
    restart: unless-stopped

  grpc-server:
    image: webide.azurecr.io/seng513-202501-group-27-grpc-server:latest
    container_name: grpc-server
    ports:
      - "8080:8080"
    restart: unless-stopped

  ui:
    image: webide.azurecr.io/seng513-202501-group-27-ui:latest
    container_name: ui
    ports:
      - "3000:3000"
    restart: unless-stopped
