# ✅ Match runtime with build to avoid GLIBC mismatch
FROM golang:1.24-bullseye AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o grpc-server ./server

# Final stage
FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/grpc-server .

EXPOSE 8080

ENTRYPOINT ["/app/grpc-server"]
