services:
  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
      target: development # or production
    ports:
      - "3000:3000" # Dev server or Nginx
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./UI:/app
      - /app/node_modules

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: grpc-server
    ports:
      - "8080:8080" # gRPC server port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./projects:/tmp/projects
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    ports:
      - "8081:8081" # gRPC-Web entry point
      - "9901:9901" # Admin
    volumes:
      - ./docker/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - grpc-server
    restart: unless-stopped
