/**
 * @fileoverview gRPC-Web generated client stub for logs
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.6
// source: dockerLogs.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as dockerLogs_pb from './dockerLogs_pb'; // proto import: "dockerLogs.proto"


export class DockerLogServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreamDockerLogs = new grpcWeb.MethodDescriptor(
    '/logs.DockerLogService/StreamDockerLogs',
    grpcWeb.MethodType.SERVER_STREAMING,
    dockerLogs_pb.DockerLogRequest,
    dockerLogs_pb.DockerLogEntry,
    (request: dockerLogs_pb.DockerLogRequest) => {
      return request.serializeBinary();
    },
    dockerLogs_pb.DockerLogEntry.deserializeBinary
  );

  streamDockerLogs(
    request: dockerLogs_pb.DockerLogRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<dockerLogs_pb.DockerLogEntry> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/logs.DockerLogService/StreamDockerLogs',
      request,
      metadata || {},
      this.methodDescriptorStreamDockerLogs);
  }

}

