/**
 * @fileoverview gRPC-Web generated client stub for filetree
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.6
// source: filetree.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as filetree_pb from './filetree_pb'; // proto import: "filetree.proto"


export class FileServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUpload = new grpcWeb.MethodDescriptor(
    '/filetree.FileService/Upload',
    grpcWeb.MethodType.UNARY,
    filetree_pb.UploadRequest,
    filetree_pb.UploadResponse,
    (request: filetree_pb.UploadRequest) => {
      return request.serializeBinary();
    },
    filetree_pb.UploadResponse.deserializeBinary
  );

  upload(
    request: filetree_pb.UploadRequest,
    metadata?: grpcWeb.Metadata | null): Promise<filetree_pb.UploadResponse>;

  upload(
    request: filetree_pb.UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: filetree_pb.UploadResponse) => void): grpcWeb.ClientReadableStream<filetree_pb.UploadResponse>;

  upload(
    request: filetree_pb.UploadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: filetree_pb.UploadResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/filetree.FileService/Upload',
        request,
        metadata || {},
        this.methodDescriptorUpload,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/filetree.FileService/Upload',
    request,
    metadata || {},
    this.methodDescriptorUpload);
  }

}

