/**
 * @fileoverview gRPC-Web generated client stub for filetree
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.6
// source: filetree.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as filetree_pb from './filetree_pb'; // proto import: "filetree.proto"


export class FileServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUpload = new grpcWeb.MethodDescriptor(
    '/filetree.FileService/Upload',
    grpcWeb.MethodType.SERVER_STREAMING,
    filetree_pb.UploadRequest,
    filetree_pb.UploadResponse,
    (request: filetree_pb.UploadRequest) => {
      return request.serializeBinary();
    },
    filetree_pb.UploadResponse.deserializeBinary
  );

  upload(
    request: filetree_pb.UploadRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<filetree_pb.UploadResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/filetree.FileService/Upload',
      request,
      metadata || {},
      this.methodDescriptorUpload);
  }

  methodDescriptorRedeploy = new grpcWeb.MethodDescriptor(
    '/filetree.FileService/Redeploy',
    grpcWeb.MethodType.SERVER_STREAMING,
    filetree_pb.ReuploadRequest,
    filetree_pb.UploadResponse,
    (request: filetree_pb.ReuploadRequest) => {
      return request.serializeBinary();
    },
    filetree_pb.UploadResponse.deserializeBinary
  );

  redeploy(
    request: filetree_pb.ReuploadRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<filetree_pb.UploadResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/filetree.FileService/Redeploy',
      request,
      metadata || {},
      this.methodDescriptorRedeploy);
  }

}

